# Generated by Django 3.0.5 on 2020-07-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='cdate',
            field=models.DateField(),
        ),
    ]
