# Generated by Django 3.0.5 on 2020-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200709_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
