# Generated by Django 3.0.5 on 2020-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200709_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='ctime',
            field=models.TimeField(),
        ),
    ]
